global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  external_labels:
      monitor: 'prom'
      username: 'sonbm'

# remote_write:
#   - url: "http://27.66.108.93:9090/api/v1/write"


scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: [
      "52.91.70.187:9100",
      "192.168.16.213:9100",
      "192.168.16.10:9100",
    ]

  - job_name: "cadvisor"
    static_configs:
      - targets: [
      "192.168.16.96:8080",
      "192.168.16.213:8080",
      "192.168.16.10:8080"
    ]