---
# tasks file for push_images

- name: Save Docker images
  community.docker.docker_image:
    name: "{{ item }}"
    archive_path: /tmp/{{ item }}.tar
    source: pull
    state: present
  loop:
    - source-web
    - source-backend
  
  