---
# tasks file for monitor
- name: Run cadvisor container
  community.docker.docker_container:
    image: gcr.io/cadvisor/cadvisor:latest
    name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

- name: Run node exporter container
  community.docker.docker_container:
    image: prom/node-exporter:latest
    name: node_exporter
    ports:
      - 9100:9100
    restart_policy: "unless-stopped"

- name: Run Prometheus container
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus
    restart: true
    published_ports: "9090:9090"
    volumes:
      - "./roles/monitor/templates/prometheus.yml:/etc/prometheus/prometheus.yml"


