---
# tasks file for db
- name: Create a network
  community.docker.docker_network:
    name: my-network
    state: present
    
- name: Download Docker image from Docker Hub
  docker_image:
    name: mongo:5.0.6
    source: pull

- name: Run Mongo container
  community.docker.docker_container:
    name: data_tier
    image: mongo:5.0.6
    state: started
    networks:
      - name: my-network