- name: Install Docker
  hosts: all
  become: yes
  roles:
    - common

- name: Create remote database
  hosts: database
  become: yes
  roles:
    # Run containers and connect to the existing network
    - db

- name: Load images and deloy three-tier web in node
  hosts: 
    - localhost
    - remote_host
  become: yes
  roles:
    # Run containers and connect to the existing network
    - api
    - web

- name: Set up load balancer in host
  hosts: localhost
  become: yes
  roles:
    - lb
