- name: Install Docker
  hosts: all
  become: yes
  roles:
    - common

- name: Load images and deloy three-tier web in node
  hosts: nodes
  become: yes
  roles:
    # Set up network for containers in nodes
    - set_up_network
    - db
    # Run containers and connect to the existing network
    - api
    - web

  - name: Set up load balancer in host
    hosts: host
    become: yes
    roles:
      - lb
