---


# - name: Install Docker
#   hosts: all
#   become: yes
#   roles:
#     - common

- name: log
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - logging

- name: Create remote only-one database
  hosts: database
  become: yes
  roles:
    - db

- name: Load images and deloy three-tier web in node
  hosts: 
    - host
    - remote_nodes
  become: yes
  roles:
    # Run containers and connect to the existing network
    - api
    - web

- name: Set up load balancer in host
  hosts: host
  become: yes
  roles:
    - lb
