---
# tasks file for set_up_network
- name: Create /etc/nginxconf folder
  file:
    path: /etc/nginxconf
    state: directory
  become: true

- name: Copy nginx.conf to host
  template:
    src: nginx.conf
    dest: /etc/nginxconf/nginx.conf

- name: Run nginx load balancing
  docker_container:
    name: nginxlb
    image: nginx:1.22.0-alpine
    restart_policy: unless-stopped
    volumes:
      - /etc/nginxconf/nginx.conf:/etc/nginx/conf.d/default.conf
    command: ["nginx", "-g", "daemon off;"]
  become: true