name: Build and Release

on:
  push:
    tags:
      - '*'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "TAG=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            backend:${{ env.TAG }}
            frontend:${{ env.TAG }}
          file: |
            10.GK/PhamDuyCuong/source/web_CRUD/api/Flask_CRUD/
            10.GK/PhamDuyCuong/source/web_CRUD/web/