name: Build and Release

on:
  push:
    tags:
      - '*'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push backend images
        uses: docker/build-push-action@v4
        with:
          context: 10.GK/PhamDuyCuong/source/web_CRUD/
          push: true
          file: |
            app/api/Dockerfile
            app/web/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.ref:10: }}
            ${{ secrets.DOCKERHUB_USERNAME }}/fronend:${{ github.ref:10: }}
