name: CI workflow

on:
  pull_request:
    branches:
      - main
      - 10.GK
  
  push:
    branches:
     - main
     - 10.GK

permissions:
  contents: read

jobs:
  unit_testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mongomock
          pip install -r 10.GK/PhamDuyCuong/source/Web_CRUD/api/requirements.txt

      - name: Run tests
      - name: Run unit test
        run: |
          python -m unittest 10.GK/PhamDuyCuong/source/Web_CRUD/api/tests.py